[project]
name = "CmdManager"
version = "0.1.0"
description = "Collect your personal commands."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "psutil>=7.0.0",
 "pystray>=0.19.5",
 "pywin32>=310",
]
